{
 "title": "FastAPI Monitoring - Minimal",
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(api_requests_total[1m])", "legendFormat": "{{http_status}}" }
   ]
  },
  {
   "title": "Errors 500",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(api_requests_total{http_status=\"500\"})",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Successful 200",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(api_requests_total{http_status=\"200\"})",
     "legendFormat": "200"
    }
   ]
  },
  {
   "title": "Average Latency (s)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(api_request_duration_seconds_sum[1m]) / rate(api_request_duration_seconds_count[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Requests per Status Code",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(api_requests_total[1m])", "legendFormat": "{{http_status}}" }
   ]
  }
 ]
}